/**
 * Utility to export project script content as a formatted Microsoft Word (.docx / .doc) document
 */
export function exportScriptToWord(project: {
  name: string;
  client_name?: string;
  deadline?: string | null;
  priority?: string;
  description?: string;
  script_content?: string;
}) {
  const title = project.name || 'Untitled Script';
  const clientInfo = project.client_name ? `<p><strong>Client:</strong> ${project.client_name}</p>` : '';
  const deadlineInfo = project.deadline ? `<p><strong>Deadline:</strong> ${project.deadline}</p>` : '';
  const priorityInfo = project.priority ? `<p><strong>Priority:</strong> ${project.priority}</p>` : '';
  const descInfo = project.description ? `<p><strong>Description:</strong> ${project.description}</p>` : '';

  const rawScript = project.script_content || 'No script content provided.';
  // Convert newlines to paragraphs/breaks
  const formattedScript = rawScript
    .split('\n\n')
    .map((block) => `<p style="margin-bottom: 12pt; line-height: 1.5;">${block.replace(/\n/g, '<br/>')}</p>`)
    .join('');

  const htmlContent = `
    <!DOCTYPE html>
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body {
          font-family: 'Calibri', 'Arial', sans-serif;
          font-size: 11pt;
          color: #111111;
          margin: 40pt;
          line-height: 1.5;
        }
        h1 {
          font-size: 20pt;
          color: #0f172a;
          border-bottom: 2pt solid #0f172a;
          padding-bottom: 6pt;
          margin-bottom: 16pt;
        }
        h2 {
          font-size: 14pt;
          color: #334155;
          margin-top: 20pt;
          margin-bottom: 8pt;
          border-bottom: 1pt solid #e2e8f0;
          padding-bottom: 4pt;
        }
        .meta-table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20pt;
          background-color: #f8fafc;
          padding: 10pt;
          border: 1pt solid #cbd5e1;
        }
        .meta-table td {
          padding: 6pt 10pt;
          font-size: 10pt;
        }
        .script-box {
          padding: 14pt;
          border-left: 3pt solid #2563eb;
          background-color: #fdfdfd;
          font-size: 11pt;
        }
        .footer {
          margin-top: 30pt;
          font-size: 9pt;
          color: #64748b;
          text-align: right;
          border-top: 1pt solid #e2e8f0;
          padding-top: 6pt;
        }
      </style>
    </head>
    <body>
      <h1>${title}</h1>

      <table class="meta-table">
        <tr>
          <td><strong>Project:</strong> ${title}</td>
          <td>${clientInfo}</td>
        </tr>
        <tr>
          <td>${deadlineInfo}</td>
          <td>${priorityInfo}</td>
        </tr>
        ${descInfo ? `<tr><td colspan="2">${descInfo}</td></tr>` : ''}
      </table>

      <h2>Script & Production Breakdown</h2>
      <div class="script-box">
        ${formattedScript}
      </div>

      <div class="footer">
        Generated by Editor OS • ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff', htmlContent], {
    type: 'application/msword'
  });

  const filename = `${title.toLowerCase().replace(/[^a-z0-9]/gi, '_')}_script.doc`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
